In [2]:
import pandas as pd
lst=[[101,'Vilas','PK',22,'Python','knr'],
     [102,'Thejus','PK',20,'Python','ekm'],
     [103,'Sreerag','PK',19,'Javascript','knr'],
     [104,'Sanay','S',22,'ACC','knr'],
     [105,'Ashwin','A',20,'DS','wyd'],
     [106,'Kelly','A',19,'java','Mlp'],
     [107,'Surya','P',14,'c','Mlp'],
     ]
df=pd.DataFrame(lst)
df

     0        1   2   3           4    5
0  101    Vilas  PK  22      Python  knr
1  102   Thejus  PK  20      Python  ekm
2  103  Sreerag  PK  19  Javascript  knr
3  104    Sanay   S  22         ACC  knr
4  105   Ashwin   A  20          DS  wyd
5  106    Kelly   A  19        java  Mlp
6  107    Surya   P  14           c  Mlp

In [3]:
df.describe()

                0          3
count    7.000000   7.000000
mean   104.000000  19.428571
std      2.160247   2.699206
min    101.000000  14.000000
25%    102.500000  19.000000
50%    104.000000  20.000000
75%    105.500000  21.000000
max    107.000000  22.000000