In [12]:
#join ----- combine df

# inner join --- returns matching rows from both df
# left join  --- returns all the rows from left table and also matching rows from right table.if no match return null
# right join --- returns all the rows from right table and also matching rows from left table.if no return null
# full join  --- returns all rows from both the df.if no return null

In [13]:
import pandas as pd

df1_data = {
    "id": [1, 2, 3, 4, 5],
    "fname": ["Vilas", "Aman", "Neha", "Rahul", "Anu"],
    "age": [22, 24, 23, 25, 21]
}
df1_data

{'id': [1, 2, 3, 4, 5],
 'fname': ['Vilas', 'Aman', 'Neha', 'Rahul', 'Anu'],
 'age': [22, 24, 23, 25, 21]}

In [14]:
df2_data = {
    "id": [3, 4, 5, 6, 7],
    "prof": ["Analyst", "ML Eng", "Dev", "Tester", "Manager"],
    "sal": [60000, 85000, 70000, 50000, 90000]
}

In [15]:
df1 = pd.DataFrame(df1_data)
print(df1)

   id  fname  age
0   1  Vilas   22
1   2   Aman   24
2   3   Neha   23
3   4  Rahul   25
4   5    Anu   21

In [16]:
df2 = pd.DataFrame(df2_data)
print(df2)

   id     prof    sal
0   3  Analyst  60000
1   4   ML Eng  85000
2   5      Dev  70000
3   6   Tester  50000
4   7  Manager  90000

In [ ]:
# inner join

new_DF=pd.merge(df1,df2,on='id',how='inner')
new_DF

   id  fname  age     prof    sal
0   3   Neha   23  Analyst  60000
1   4  Rahul   25   ML Eng  85000
2   5    Anu   21      Dev  70000

In [18]:
# outer join
new_dfo=pd.merge(df1,df2,on='id',how='outer')
new_dfo

   id  fname   age     prof      sal
0   1  Vilas  22.0      NaN      NaN
1   2   Aman  24.0      NaN      NaN
2   3   Neha  23.0  Analyst  60000.0
3   4  Rahul  25.0   ML Eng  85000.0
4   5    Anu  21.0      Dev  70000.0
5   6    NaN   NaN   Tester  50000.0
6   7    NaN   NaN  Manager  90000.0