In [14]:
import numpy as np
import pandas as pd
df=pd.read_csv('glass.csv')
df.head()

        RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [15]:
x=df.drop(columns='Type')
x

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0
..       ...    ...   ...   ...    ...   ...   ...   ...  ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0

[214 rows x 9 columns]

In [16]:
y=df['Type']
y

0      1
1      1
2      1
3      1
4      1
      ..
209    7
210    7
211    7
212    7
213    7
Name: Type, Length: 214, dtype: int64

In [17]:
df.isna().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [19]:
x_train.ndim

2

In [20]:
y_test.ndim

1

In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
scaler.transform(x_train)
scaler.transform(x_test)

array([[ 2.96144632e+00,  3.95808772e-01, -1.94335173e+00,
        -1.93943531e-01, -1.94002878e+00, -5.17922689e-01,
         3.60133611e+00, -3.53750449e-01,  4.42709887e-01],
       [-9.60374453e-01, -1.70671354e-01,  5.66239839e-01,
         2.54308287e-02,  7.76791661e-01, -1.98758751e-01,
        -7.04764852e-01, -3.53750449e-01, -5.69004426e-01],
       [-2.88598455e-01, -6.38633196e-01,  6.16575487e-01,
        -3.73431643e-01,  7.22725582e-01,  7.00108815e-02,
        -4.26181611e-01, -3.53750449e-01,  1.15090991e+00],
       [-4.34963058e-01, -4.66226202e-01,  5.51858226e-01,
         6.63610784e-01,  6.04161212e-02,  2.71588106e-01,
        -5.85372034e-01, -3.53750449e-01, -5.69004426e-01],
       [-9.52868576e-01, -8.11040191e-01,  5.44667419e-01,
         2.04918941e-01,  7.09209063e-01,  2.88386208e-01,
        -6.57007725e-01, -3.53750449e-01,  1.85910993e+00],
       [-2.28551438e-01, -4.90855772e-01,  6.02193873e-01,
        -4.93090385e-01,  4.38878670e-01,  2.54790004e-01,
        -3.06788793e-01, -3.53750449e-01, -5.69004426e-01],
       [-1.05044498e+00,  9.37659326e-01, -1.94335173e+00,
         2.43854878e+00,  9.66022935e-01, -7.02701811e-01,
         1.23025351e-01,  8.15001944e-01, -6.31472692e-02],
       [-6.93915817e-01,  1.22089939e+00, -1.94335173e+00,
         2.55820753e+00,  2.36130876e-01, -8.37086627e-01,
         4.25487156e-01,  6.80882817e-01, -5.69004426e-01],
       [ 1.53895668e-02, -1.70671354e-01,  8.61062917e-01,
        -9.42279128e-02, -4.66728144e-01,  8.68089835e-02,
        -4.81898259e-01, -3.53750449e-01,  4.42709887e-01],
       [-6.71398186e-01,  3.86799969e-02,  6.09384680e-01,
        -4.13317890e-01,  1.82064798e-01,  3.05184310e-01,
        -6.49048204e-01, -3.53750449e-01, -5.69004426e-01],
       [-2.66080824e-01,  1.24883494e-01,  7.46010009e-01,
        -5.72862879e-01,  4.25362151e-01,  1.54001392e-01,
        -7.04764852e-01, -3.53750449e-01, -5.69004426e-01],
       [ 8.18518414e-01,  1.73564089e-03, -1.94335173e+00,
        -1.14171036e-01, -5.74860301e-01, -2.82749261e-01,
         2.85314112e+00, -3.53750449e-01, -5.69004426e-01],
       [-1.72257360e-01,  3.21920060e-01,  6.81292748e-01,
        -1.60990531e+00,  4.38878670e-01, -7.36298015e-01,
         1.15920543e-02, -3.53750449e-01, -5.69004426e-01],
       [ 3.43056364e+00, -2.90455370e+00, -1.94335173e+00,
        -1.41047407e+00,  5.47010827e-01, -8.37086627e-01,
         4.81118333e+00, -3.53750449e-01, -5.69004426e-01],
       [-6.11351169e-01, -6.50947982e-01,  5.80621453e-01,
        -3.43985420e-02,  4.52395190e-01,  3.05184310e-01,
        -5.45574428e-01, -2.38791198e-01,  1.96028136e+00],
       [-6.00092353e-01, -2.93819207e-01,  5.37476612e-01,
         6.03781413e-01, -2.63980350e-01,  1.70799494e-01,
        -4.26181611e-01, -3.53750449e-01,  1.15090991e+00],
       [-6.37621739e-01, -7.74095835e-01,  1.06028205e-01,
        -3.43985420e-02,  8.03824700e-01,  1.20405188e-01,
        -9.98412422e-02, -1.42991821e-01,  1.65676706e+00],
       [-4.42468935e-01,  1.24883494e-01,  5.59049032e-01,
         5.04065795e-01, -2.09914271e-01,  2.04395698e-01,
        -7.36602937e-01, -3.53750449e-01, -5.69004426e-01],
       [-1.72257360e-01, -2.07615710e-01,  4.94331771e-01,
        -2.53772902e-01,  1.14482200e-01,  1.54001392e-01,
        -2.59031666e-01, -3.53750449e-01, -5.69004426e-01],
       [ 1.78302362e+00, -8.44678564e-02,  6.30957100e-01,
        -1.27087220e+00, -9.26289811e-01, -6.35509403e-01,
         9.98572681e-01, -3.53750449e-01, -2.65490132e-01],
       [ 6.34624425e-01, -1.33726998e-01, -1.94335173e+00,
         6.03781413e-01,  4.79428229e-01, -4.75758325e-02,
         1.91391762e+00, -3.53750449e-01, -5.69004426e-01],
       [-5.96339415e-01, -6.38633196e-01, -1.94335173e+00,
         7.43383278e-01,  1.62833240e+00,  7.92329268e-01,
         9.98572681e-01, -3.53750449e-01, -5.69004426e-01],
       [-6.75151124e-01,  7.56243529e-02,  6.52529521e-01,
         1.65032694e-01, -3.85629026e-01,  2.71588106e-01,
        -7.04764852e-01, -3.53750449e-01, -5.69004426e-01],
       [ 1.22758871e+00, -4.04652275e-01,  6.81292748e-01,
        -1.17115659e+00, -6.15409859e-01, -5.17922689e-01,
         7.43868003e-01, -3.53750449e-01,  1.15090991e+00],
       [-7.76480465e-01,  1.86457421e-01,  6.09384680e-01,
         1.65032694e-01,  4.25362151e-01, -1.81960649e-01,
        -9.03752881e-01, -3.53750449e-01, -5.69004426e-01],
       [-9.34456508e-02,  4.08123557e-01,  8.82635338e-01,
         1.65032694e-01, -1.16958716e+00,  7.00108815e-02,
        -5.61493471e-01, -3.53750449e-01,  9.48567044e-01],
       [ 1.76765924e-01, -5.52429699e-01,  6.88483554e-01,
         2.04918941e-01, -2.23430791e-01,  1.37203290e-01,
        -2.90869751e-01, -3.53750449e-01,  6.45052750e-01],
       [-1.89110321e+00, -4.66226202e-01, -1.94335173e+00,
         3.11661499e+00, -2.66992084e+00,  9.59453472e+00,
        -1.58031218e+00, -3.53750449e-01, -5.69004426e-01],
       [ 2.74342326e-01,  2.48031348e-01,  4.65568544e-01,
        -4.53204137e-01, -8.04641134e-01,  1.54001392e-01,
        -4.32698802e-03, -3.53750449e-01, -5.69004426e-01],
       [-1.34727975e-01, -2.32245280e-01,  8.61062917e-01,
        -3.13602272e-01, -4.66728144e-01,  8.68089835e-02,
        -3.78424484e-01, -3.53750449e-01,  2.26379565e+00],
       [ 1.58411788e+00,  1.82432387e+00, -3.61374236e-01,
         1.20207512e+00, -3.26464770e+00,  4.39569126e-01,
         6.72232312e-01, -3.53750449e-01, -5.69004426e-01],
       [-6.75151124e-01,  1.92284215e+00, -1.94335173e+00,
         8.23155772e-01,  5.87560386e-01, -8.37086627e-01,
        -1.95355496e-01,  2.29031234e+00, -5.69004426e-01],
       [-6.71398186e-01, -4.16967060e-01,  5.01522578e-01,
        -3.93374767e-01,  4.52395190e-01,  3.64146775e-02,
        -2.66991187e-01, -3.53750449e-01, -5.69004426e-01],
       [ 5.88498544e+00, -1.32826118e+00, -1.94335173e+00,
        -9.11895980e-01, -3.39981290e+00, -6.35509403e-01,
         5.79020443e+00, -3.53750449e-01,  1.85910993e+00],
       [-8.70303928e-01, -3.55393134e-01,  6.38147907e-01,
         1.25146447e-01,  5.74043867e-01,  2.88386208e-01,
        -8.63955276e-01, -3.53750449e-01, -5.69004426e-01],
       [-6.26362923e-01,  1.75043516e+00, -1.94335173e+00,
         1.06247326e+00,  5.87560386e-01, -8.37086627e-01,
        -5.05776822e-01,  2.92258823e+00, -5.69004426e-01],
       [-5.70068845e-01, -9.67826418e-02,  6.74101941e-01,
         1.45089570e-01, -1.96397751e-01,  2.54790004e-01,
        -7.04764852e-01, -3.53750449e-01,  2.36496708e+00],
       [ 1.49404735e+00, -2.07615710e-01,  7.67582429e-01,
        -1.33070158e+00, -9.26289811e-01, -6.18711301e-01,
         8.79179863e-01, -3.53750449e-01, -5.69004426e-01],
       [ 1.31730661e-01, -2.28939298e-02,  5.23094998e-01,
        -5.43416656e-02, -5.61343781e-01,  1.96165755e-02,
        -2.51072145e-01, -3.53750449e-01, -5.69004426e-01],
       [ 5.70824470e-01,  5.31271410e-01,  6.30957100e-01,
        -2.73716025e-01, -1.29123584e+00, -6.35509403e-01,
        -1.95355496e-01,  9.68280946e-01, -5.69004426e-01],
       [-8.81562744e-01, -6.87892338e-01,  5.87812259e-01,
         8.82985143e-01,  2.49647396e-01,  3.21982412e-01,
        -7.52521979e-01, -3.53750449e-01, -5.69004426e-01],
       [ 3.16035206e+00,  7.52937546e-01,  7.17246782e-01,
        -1.49024656e+00, -1.49398363e+00, -8.03490423e-01,
         7.19989439e-01, -3.53750449e-01,  4.42709887e-01],
       [-7.35198141e-01, -8.23354976e-01,  4.51186931e-01,
         6.53170759e-02,  8.17341220e-01,  2.88386208e-01,
        -5.37614907e-01, -3.53750449e-01, -5.69004426e-01],
       [-2.21045561e-01, -2.07615710e-01,  7.10055975e-01,
        -3.33545396e-01, -8.82655945e-02,  1.20405188e-01,
        -5.53533950e-01, -3.53750449e-01, -5.69004426e-01],
       [ 1.44901209e+00,  9.99233253e-01,  7.74773236e-01,
        -1.09138409e+00, -1.77783055e+00, -4.50730281e-01,
         1.78741999e-01, -3.53750449e-01,  3.17433853e+00],
       [-5.81327661e-01, -1.70671354e-01,  6.23766293e-01,
        -1.54057284e-01,  3.33830820e-02,  1.03607086e-01,
        -3.78424484e-01, -3.53750449e-01,  4.42709887e-01],
       [-1.97366786e+00,  1.25784374e+00, -6.92151349e-01,
         1.65032694e-01,  2.53393921e+00, -8.37086627e-01,
        -1.05498378e+00, -3.53750449e-01, -5.69004426e-01],
       [ 1.32141218e+00, -2.19930495e-01,  7.02865168e-01,
        -6.12749126e-01,  1.00965680e-01,  7.00108815e-02,
        -3.14748314e-01, -3.53750449e-01, -5.69004426e-01],
       [-3.48645471e-01,  1.93515694e+00, -1.94335173e+00,
         6.83553907e-01,  4.25362151e-01, -8.37086627e-01,
        -2.43112623e-01,  2.61603022e+00, -5.69004426e-01],
       [-5.06268890e-01, -5.98382858e-02,  6.02193873e-01,
         3.04634559e-01, -1.82881232e-01,  3.05184310e-01,
        -6.41088682e-01, -3.53750449e-01, -5.69004426e-01],
       [ 3.49401097e-01,  8.14511473e-01,  6.30957100e-01,
        -1.74000407e-01, -8.04641134e-01,  1.03607086e-01,
        -4.89857780e-01, -3.53750449e-01, -5.69004426e-01],
       [-6.75151124e-01,  2.63652116e-02,  5.66239839e-01,
         1.25146447e-01, -3.41995161e-02,  2.88386208e-01,
        -6.64967246e-01, -3.53750449e-01,  4.42709887e-01],
       [-3.37386656e-01, -4.41596631e-01,  6.02193873e-01,
         4.64179548e-01,  7.39326408e-02,  7.00108815e-02,
        -3.78424484e-01, -3.53750449e-01,  1.39195593e-01],
       [ 2.66483824e-02, -5.98382858e-02,  4.58377737e-01,
         1.65032694e-01, -7.23542016e-01,  1.03607086e-01,
         5.93491814e-02, -3.53750449e-01, -5.69004426e-01],
       [-9.67880330e-01, -1.09097427e-01,  5.37476612e-01,
        -4.93090385e-01,  8.74491605e-02,  1.03607086e-01,
        -2.74950708e-01, -3.53750449e-01, -5.69004426e-01],
       [-2.66420855e+00,  4.92764977e+00, -1.94335173e+00,
        -2.22814214e+00,  3.69635990e+00, -8.37086627e-01,
        -1.80317877e+00, -3.53750449e-01, -5.69004426e-01],
       [ 9.79542146e-02, -2.19930495e-01,  6.66911134e-01,
        -7.72294115e-01,  2.09097837e-01,  1.20405188e-01,
        -4.02303047e-01, -1.81311572e-01,  1.15090991e+00],
       [ 1.85808239e+00,  4.20438342e-01,  7.31628395e-01,
        -1.88910904e+00, -1.25068628e+00, -6.85903709e-01,
         9.11017948e-01, -3.53750449e-01,  1.04973847e+00],
       [ 1.13376525e+00,  1.15932546e+00,  8.61062917e-01,
        -1.25092908e+00, -1.58859927e+00, -8.37086627e-01,
         4.57325240e-01, -3.53750449e-01, -5.69004426e-01],
       [ 3.57317530e+00, -9.09558474e-01, -1.94335173e+00,
        -1.57001906e+00, -8.85740252e-01, -7.36298015e-01,
         4.36545014e+00, -3.53750449e-01, -5.69004426e-01],
       [-3.07363147e-01, -9.67826418e-02,  6.45338714e-01,
        -6.32692250e-01,  5.60527347e-01,  1.37203290e-01,
        -5.93331555e-01, -3.53750449e-01, -5.69004426e-01],
       [-1.19716221e-01, -2.07615710e-01,  5.59049032e-01,
        -9.42279128e-02, -4.77160357e-02,  1.54001392e-01,
        -3.86384005e-01, -3.53750449e-01, -5.69004426e-01],
       [-6.52633493e-01,  1.23321417e+00, -1.94335173e+00,
         9.62757638e-01,  1.26338637e+00, -8.37086627e-01,
        -3.46586399e-01,  2.65434997e+00, -5.69004426e-01],
       [ 9.01083061e-01,  1.20858460e+00, -1.94335173e+00,
         1.12230263e+00,  1.00657249e+00, -8.37086627e-01,
        -3.78424484e-01,  2.78846910e+00, -5.69004426e-01],
       [ 1.22758871e+00, -4.04652275e-01,  6.81292748e-01,
        -1.17115659e+00, -4.80244663e-01, -5.17922689e-01,
         7.43868003e-01, -3.53750449e-01,  1.15090991e+00]])

In [22]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [23]:
y_pred=knn.predict(x_test)
y_pred

array([2, 2, 1, 2, 2, 1, 7, 7, 2, 1, 2, 5, 1, 5, 1, 2, 2, 2, 1, 1, 5, 5,
       2, 1, 2, 2, 1, 7, 1, 2, 2, 7, 1, 2, 2, 7, 2, 1, 3, 1, 2, 1, 1, 2,
       1, 1, 7, 1, 7, 2, 2, 2, 1, 1, 3, 7, 1, 1, 1, 2, 1, 3, 7, 7, 1],
      dtype=int64)

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_pred,y_test)
cm

array([[13,  6,  6,  0,  0,  0],
       [ 5, 16,  1,  0,  0,  1],
       [ 2,  1,  0,  0,  0,  0],
       [ 0,  1,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  2,  7]], dtype=int64)

In [29]:
a=accuracy_score(y_pred,y_test)
a

0.6